sudo: required
dist: trusty
os:
  - linux

language: node_js
node_js:
  - '9'
  - '10'

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install: travis_retry npm install

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - HEADLESS=1 npm test

stages:
  - test
  - pack
  - name: deploy
    if: branch =~ ^(master|v\d+\.\d+) AND (type IN (push))

jobs:
  include:

    - stage: pack
      script:
        - echo "NPM Pack Testing..."
        - npm run test:pack
        - echo 'NPM Pack Testing is PASSED.'

    - stage: deploy
      script:
        - echo "Packing NPM ..."
        - npm version
        - if ./scripts/development-release.ts; then ./scripts/package-publish-config-tag-next.ts; fi
        - npm run dist
        - echo "Deploying to NPM ..."

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - ${GITTER_IM_URL}
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
