os:
  - linux

language: node_js
node_js:
  - '4'

branches:
  only:
  - master

cache:
  directories:
    - node_modules

notifications:
  webhooks:
    urls:
      - ${GITTER_IM_URL}
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
