sudo: required
dist: trusty
os:
  - linux

language: node_js
node_js:
  - '9'
  - '8'

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - node_modules

stages:
  - test
  - pack
  - name: deploy
    if: branch =~ ^(master|v\d+\.\d+)
        AND (type NOT IN (cron, pull_request))

install: travis_retry npm install

jobs:
  include:
    - stage: test
      script:
        - echo $TRAVIS_OS_NAME
        - node --version
        - npm --version
        - npm test

    - stage: pack
      script:
        - echo "NPM Pack Testing..."
        - npm run test:pack
        - echo 'NPM Pack Testing is PASSED.'

    - stage: deploy
      before_deploy:
        - echo "Packing NPM ..."
        - npm version
        - if ./scripts/development-release.ts; then ./scripts/package-publish-config-tag-next.ts; fi
        - npm run dist
        - echo "Deploying to NPM ..."

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - ${GITTER_IM_URL}
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
